export const workItems = [
    {
      title: "Upardigital",
      description: "Revolucionando la educación virtual en Uparsistem",
      category: ["consulting", "technology"],
      path: "upardigital",
      videoSrc: "/assets/videos/uparpreview.mp4",
    },
    {
      title: "Monster Energy",
      description: '"I am the Beast"',
      category: ["creativity"],
      path: "monster-energy",
      videoSrc: "/assets/videos/monsterpreview.mp4",
    },
    {
      title: "Páginas Web",
      description: "Innovación y Experiencia de Usuario de Alto Impacto",
      category: ["creativity", "technology", "consulting"],
        path: "web-page",
      videoSrc: "/assets/videos/webpagespreview.mp4",
    },
    {
      title: "Wersus",
      description: "Innovación en logística de transporte",
      category: ["creativity", "technology", "consulting"],
      path: "wersus",
      videoSrc: "https://storage.googleapis.com/antares-agency-rcs/Video%20Promo%20Wersus%20TSP_1.mp4",
    },
    {
      title: "CIML",
      description: "Innovación Editorial para la Salud Pública",
      category: ["creativity", "consulting"],
      path: "ciml",
      videoSrc: "https://storage.googleapis.com/antares-agency-rcs/CIML%20preview.mp4",
    },
    {
      title: "Politécnico Grancolombiano",
      description: "Estrategia Digital para Conectar con los Jóvenes",
      category: ["technology"],
      path: "politecnico",
      videoSrc: "https://storage.googleapis.com/antares-agency-rcs/Poli%20Preview.mp4",
    },
    {
      title: "Lili Estevez",
      description: "Concept Art para Sencillo Musical “La Señal”",
      category: ["creativity"],
      path: "lili-estevez",
      videoSrc: "https://storage.googleapis.com/antares-agency-rcs/Lili%20Preview.mp4",
    },
    {
      title: "Fundación Heinrich Böll",
      description:
        "Escuela de Administración y Gestión del Estado para Transiciones Justas",
      category: ["creativity"],
      path: "fundacion",
      videoSrc: "https://storage.googleapis.com/antares-agency-rcs/heinrich%20boll%20PREVIEW.mp4",
    },
    {
      title: "Uparsistem",
      description: "Consolidando su Identidad Universitaria",
      category: ["technology"],
      path: "uparsistem",
      videoSrc: "https://storage.googleapis.com/antares-agency-rcs/Uparsistem%20preview.mp4",
    },
    {
      title: "OIM",
      description: "Cartografía Migratoria: Impacto de la Migración Haitiana",
      category: ["creativity"],
      path: "oim",
      videoSrc: "https://storage.googleapis.com/antares-agency-rcs/IOM%20preview.mp4",
    },
    {
      title: "B2Fintech",
      description: "Conectando con el Mercado Global de Criptomonedas",
      category: ["technology"],
      path: "b2fintech",
      videoSrc: "https://storage.googleapis.com/antares-agency-rcs/2bfintech%20preview.mp4",
    },
  ];
