// import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "../components/header/Header";
// import LottieIChatbot from "../components/landing/LottieIChatbot";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={inter.className}>
//       <body>
//         <Header />
//         <LottieIChatbot/>
//         {children}
//       </body>
//     </html>
//   );
// }


import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../../components/header/Header";
import LottieIChatbot from "../../components/landing/LottieIChatbot";
import { NextIntlClientProvider } from "next-intl"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Antares Innovate",
  description: "Antares Innovate es una empresa que se dedica a la transformación digital.",
};


export default function RootLayout({ children, locale, messages }) {
  return (
    <html lang={locale} className={inter.className}> 
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          <LottieIChatbot />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}